author: "Alexey Karapetov <karapetov@gmail.com>"
description: "JSON:API Server. Supports JSON:API v1.0 (http://jsonapi.org)"
homepage: "https://github.com/f3ath/json-api-server-dart"
name: "json_api_server"
version: "0.0.2"
dependencies:
  json_api_document: "^1.0.0"
  http: "^0.12.0"
dev_dependencies:
  uuid: "^2.0.0"
  json_api: "^1.0.0"
  json_matcher: "^0.2.3"
  test: "^1.3.0"
environment:
  sdk: ">=2.0.0 <3.0.0"
