name: json_api_server
description: JSON:API Server
version: 0.1.0-dev.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_api: ^5.0.0-dev
  pedantic: ^1.9.2

dev_dependencies:
  test: ^1.6.0
